services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  docker run -d \
  --name my-postgres \
  -e POSTGRES_PASSWORD=pswrd \
  -e POSTGRES_USER=my_user \
  -e POSTGRES_DB=my_db \
  -e PGDATA=/var/lib/postgresql/data/pgdata \
  -v db-data:/var/lib/postgresql/data \
  -p 5432:5432 \
  postgres